name: aiaccounting
description: A personal expense tracker app with local SQLite storage and Provider state management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.2
  sqlite3_flutter_libs: ^0.5.30
  path: ^1.9.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  excel: ^4.0.6
  file_picker: ^8.1.7
  csv: ^6.0.0

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.4+4

flutter:
  uses-material-design: true
